### ISSUE TITLE
Cannot type in Screen

### ISSUE THREAD

**Issue by rojas70** [h2r/ein#13]
As part of the Get Started instructions I am not sure which exactly is the "screen" session mentioned below"
````
Start the screen session using the commands given in Install. Choose an arm (left or right) to use. Type `8 to tell screen to go to the left arm’s main Ein window, or `0 to go to the right arm.
```

In the "Ein Main Window (phycial right)"  under the "Wrist View" there is a "Commands:" label on the left and the right side of this screen but no text can be input here by me....

Could you clarify in the documentation

**Comment by rojas70** [comment]
I now realize it's on the actual terminal. Not sure why I could not type on it the first time.

**Comment by joberlin** [comment]
Hi! Glad you figured it out. Here's another description I'll add to the
docs.

The REPL input terminals can be accessed through screens 1 or 7 or through
the bottom text entry field in the Ein main window. The top text entry
field in the Ein window is for entering bound key commands. While focus is
in the command field, key presses will be interpreted instantly and no text
will print. Try entering w,a,s,and d.
On Jun 29, 2016 9:21 PM, "Dr. Juan Rojas" <notifications@github.com> wrote:

I now realize it's on the actual terminal. Not sure why I could not type on
it the first time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/h2r/ein/issues/13#issuecomment-229535169>, or mute the
thread
<https://github.com/notifications/unsubscribe/AH22kcnLzO5QHxEbc2Q3yW06Kdtnc7giks5qQxoIgaJpZM4JA9jV>
.
