### ISSUE TITLE
Right camera does not open automaticaly

### ISSUE THREAD

**Issue by lyh458** [h2r/ein#15]
In the Calibration tutorial (http://h2r.github.io/ein/calibration/), in section "Set the camera parameters", we noticed that after selecting custom camera parameters, such as `80 25 1124 1024 2048 fixCameraLighting`,  the Wrist View did not update. 

So we checked which cameras were open and we noticed the right camera was closed. We started the program with either of the following two commands: `BAXTER=your_baxter screen -c src/ein/ein_baxter.screenrc` and `catkin_make && gdb --args ./devel/lib/ein/ein  _data_directory:="$(rospack find ein)/default" physical right`.

We currently open the right camera manually with baxter camera control: `rosrun baxter_tools camera_control.py -o right_hand_camera -r 640x400`

**Comment by stefie10** [comment]
The Baxter robot only allows two of the three cameras to be open at one time:  left hand, right hand, and head.  Ein tries to make this happen, but sometimes the robot doesn't listen to camera control commands.  We think this is a Rethink problem. 

So before starting Ein, you should use camera_control.py to make sure that the camera you want to use with Ein is open (left or right).  You should close the head camera and open the other two.  Sometimes it takes several tries to get the robot to do this.  

Leaving this bug open, because we should add this to the FAQ and possibly send a bug report to Rethink...

**Comment by stefie10** [comment]
Closing because I added an FAQ entry and also reported a bug to Rethink.
